type declaration = Inferred | Required | Local_required | Trusted_extern

type rule = {
  name : string;
  declaration : declaration;
  declaration_role : bool;
  function_pointer : bool;
  propagates : bool;
  effect_free_forbidden : bool;
  excludes_declared : string list;
  excludes_reachable : string list;
  rejects_unknown_indirect : bool;
  forbids_reentry : bool;
}

let rules = [
  { name = "may_block"; declaration = Inferred; declaration_role = false;
    function_pointer = true; propagates = true; effect_free_forbidden = true;
    excludes_declared = []; excludes_reachable = [];
    rejects_unknown_indirect = false; forbids_reentry = false };
  { name = "allocates"; declaration = Inferred; declaration_role = false;
    function_pointer = true; propagates = true; effect_free_forbidden = true;
    excludes_declared = []; excludes_reachable = [];
    rejects_unknown_indirect = false; forbids_reentry = false };
  { name = "locks"; declaration = Inferred; declaration_role = false;
    function_pointer = true; propagates = true; effect_free_forbidden = true;
    excludes_declared = []; excludes_reachable = [];
    rejects_unknown_indirect = false; forbids_reentry = false };
  { name = "logs"; declaration = Inferred; declaration_role = false;
    function_pointer = true; propagates = true; effect_free_forbidden = true;
    excludes_declared = []; excludes_reachable = [];
    rejects_unknown_indirect = false; forbids_reentry = false };
  { name = "requires_mmu"; declaration = Inferred; declaration_role = false;
    function_pointer = true; propagates = true; effect_free_forbidden = false;
    excludes_declared = []; excludes_reachable = [];
    rejects_unknown_indirect = false; forbids_reentry = false };
  { name = "unsafe"; declaration = Local_required; declaration_role = false;
    function_pointer = true; propagates = true; effect_free_forbidden = false;
    excludes_declared = []; excludes_reachable = [];
    rejects_unknown_indirect = false; forbids_reentry = false };
  { name = "interrupt"; declaration = Required; declaration_role = true;
    function_pointer = false; propagates = false; effect_free_forbidden = false;
    excludes_declared = ["may_block"; "allocates"; "logs"; "exception"; "mmu_off"];
    excludes_reachable = ["may_block"; "allocates"; "logs"];
    rejects_unknown_indirect = true; forbids_reentry = false };
  { name = "exception"; declaration = Required; declaration_role = true;
    function_pointer = false; propagates = false; effect_free_forbidden = false;
    excludes_declared = ["may_block"; "allocates"; "logs"; "interrupt"; "mmu_off"];
    excludes_reachable = ["may_block"; "allocates"; "logs"];
    rejects_unknown_indirect = true; forbids_reentry = true };
  { name = "mmu_off"; declaration = Required; declaration_role = true;
    function_pointer = false; propagates = false; effect_free_forbidden = false;
    excludes_declared = ["interrupt"; "exception"; "requires_mmu"];
    excludes_reachable = ["requires_mmu"];
    rejects_unknown_indirect = true; forbids_reentry = false };
  { name = "noreturn"; declaration = Trusted_extern; declaration_role = false;
    function_pointer = false; propagates = false; effect_free_forbidden = false;
    excludes_declared = []; excludes_reachable = [];
    rejects_unknown_indirect = false; forbids_reentry = false };
]

let find name = List.find_opt (fun rule -> rule.name = name) rules
let names = List.map (fun rule -> rule.name) rules
let propagating = List.filter_map (fun rule ->
  if rule.propagates then Some rule.name else None) rules
let effect_free_forbidden = List.filter_map (fun rule ->
  if rule.effect_free_forbidden then Some rule.name else None) rules

let yes_no = function true -> "yes" | false -> "no"
let declaration_text = function
  | Inferred -> "inferred"
  | Required -> "explicit"
  | Local_required -> "local explicit + inferred"
  | Trusted_extern -> "trusted extern only"
let list_text = function [] -> "-" | xs -> String.concat ", " xs

let markdown () =
  let b = Buffer.create 4096 in
  Buffer.add_string b
    "<!-- GENERATED by takibi --emit-effect-matrix. Do not edit. -->\n\n# Effect relations\n\n";
  Buffer.add_string b
    "| Effect | Declaration | Declaration role | Function pointer row | Propagates | Excludes when co-declared | Forbidden in reachable calls | Unknown indirect call | Re-entry |\n";
  Buffer.add_string b
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n";
  List.iter (fun rule ->
    Printf.bprintf b "| `%s` | %s | %s | %s | %s | %s | %s | %s | %s |\n"
      rule.name (declaration_text rule.declaration)
      (yes_no rule.declaration_role) (yes_no rule.function_pointer)
      (yes_no rule.propagates) (list_text rule.excludes_declared)
      (list_text rule.excludes_reachable)
      (if rule.rejects_unknown_indirect then "rejected" else "allowed")
      (if rule.forbids_reentry then "forbidden" else "allowed")) rules;
  Buffer.add_string b
    "\nA bare `!{}` contract forbids the transitive effects: ";
  Buffer.add_string b (String.concat ", " (List.map (Printf.sprintf "`%s`") effect_free_forbidden));
  Buffer.add_string b
    ". `locks` propagates and is forbidden by `!{}`, but is intentionally allowed from `interrupt` and `exception` roots.\n";
  Buffer.contents b
