#!/usr/bin/env python3
"""
Generate AArch64 exception-frame offset constants from the Takibi struct
definition (GitHub issue #286).

Parses kernel/arch/arm64/kernel/exception_frame.tkb's ExceptionFrame struct
and writes kernel/arch/arm64/kernel/exception_context_offsets.inc with the
computed .equ constants. That generated file is gitignored and `.include`d
by kernel/arch/arm64/kernel/exception_context.inc, which is an ordinary,
hand-written, git-tracked source file holding the SAVE/RESTORE macro bodies.

This script owns ONLY the offset constants -- it never invents or preserves
hand-written assembly logic. That split keeps a missing/deleted generated
file a harmless, obviously-broken `.include` (assembler error: file not
found) instead of a silent fallback to placeholder macros.
"""

import re
import sys
from pathlib import Path

def parse_struct_fields(tkb_path):
    """Parse ExceptionFrame struct from .tkb file and return field list."""
    with open(tkb_path, 'r') as f:
        content = f.read()

    struct_match = re.search(
        r'struct\s+packed\s+ExceptionFrame\s*\{([^}]+)\}',
        content,
        re.DOTALL
    )
    if not struct_match:
        raise ValueError("Could not find 'struct packed ExceptionFrame' in " + str(tkb_path))

    struct_body = struct_match.group(1)
    fields = []

    for line in struct_body.split('\n'):
        line = re.sub(r'//.*', '', line).strip()
        if not line:
            continue

        # Match "name: type;" pairs, type is either [u8; 16] or a bare word
        field_pattern = r'(\w+):\s+(\[[^\]]*\]|\w+);'
        for match in re.finditer(field_pattern, line):
            name, field_type = match.groups()
            fields.append((name.strip(), field_type.strip()))

    if not fields:
        raise ValueError("Could not parse any fields from ExceptionFrame struct")

    return fields

def calculate_offsets(fields):
    """Calculate byte offsets for each field: packed, sequential in struct
    declaration order, matching lib/llvm_gen.ml's exception_frame_offsets
    (the compiler's own codegen for `exception_entry`/`exception_restore`
    .tkb declarations) field-for-field. That OCaml function does NOT
    16-byte-align q0 mid-struct -- it only rounds the FINAL total up for
    stack-pointer alignment -- because AArch64 `str`/`ldr` on a Q register
    has no natural-alignment requirement, so there is no correctness reason
    to insert padding before q0. An earlier version of this script added
    that padding anyway "for safety"; it was a no-op for today's field set
    (which already lands q0 on a 16-byte boundary by coincidence) but was a
    real, if latent, divergence risk against the compiler's actual
    algorithm for any future struct shape where the two would have computed
    different offsets for the same fields. Keeping both implementations
    doing the same simple, branch-free sum is what keeps that risk small.
    """
    offsets = {}
    current_offset = 0

    for name, field_type in fields:
        is_q_array = '[u8;' in field_type and '16' in field_type

        if is_q_array:
            offsets[name] = current_offset
            current_offset += 16
        elif field_type == 'usize':
            offsets[name] = current_offset
            current_offset += 8
        else:
            raise ValueError(f"Unsupported field type: {field_type} (in field {name})")

    total_size = ((current_offset + 15) // 16) * 16
    return offsets, total_size

def generate_offsets_file(fields, offsets, total_size):
    """Generate the offsets-only assembly .inc file content."""
    lines = [
        "/* GENERATED by scripts/gen_exception_frame.py from",
        " * kernel/arch/arm64/kernel/exception_frame.tkb's ExceptionFrame struct",
        " * (GitHub issue #286). Do not edit by hand -- edit the struct instead",
        " * and re-run the generator (kernel builds do this automatically via",
        " * the Makefile's kernel-gen-exception-frame target).",
        " *",
        " * This file is gitignored: it holds ONLY offset constants, never",
        " * hand-written assembly logic, so a missing/stale copy is always safe",
        " * to regenerate from the struct with no information loss. The actual",
        " * SAVE/RESTORE macro bodies live in the ordinary, git-tracked",
        " * kernel/arch/arm64/kernel/exception_context.inc, which `.include`s",
        " * this file rather than defining these constants itself.",
        " */",
        f"    .equ EXC_CONTEXT_SIZE,          0x{total_size:x}",
    ]

    for name, field_type in fields:
        offset = offsets[name]
        const_name = f"EXC_CONTEXT_{name.upper()}"
        lines.append(f"    .equ {const_name},          0x{offset:03x}")

    return '\n'.join(lines) + '\n'

def main():
    repo_root = Path(__file__).parent.parent
    tkb_path = repo_root / "kernel" / "arch" / "arm64" / "kernel" / "exception_frame.tkb"
    offsets_inc_path = repo_root / "kernel" / "arch" / "arm64" / "kernel" / "exception_context_offsets.inc"

    if not tkb_path.exists():
        print(f"Error: {tkb_path} not found", file=sys.stderr)
        sys.exit(1)

    try:
        fields = parse_struct_fields(tkb_path)
        offsets, total_size = calculate_offsets(fields)
        content = generate_offsets_file(fields, offsets, total_size)

        # Skip the write (and its noise) if content is already up to date.
        if offsets_inc_path.exists() and offsets_inc_path.read_text() == content:
            sys.exit(0)

        offsets_inc_path.write_text(content)
        print(f"Generated {offsets_inc_path}")

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
